### PR TITLE
#8: Add capability to compare computed distributions with other tools

### LINKED ISSUE #8: Add capability to compare computed distributions with other tools
The goal of this issue to introduce, ultimately as past of Ct, the ability to compare the computed optima vs
* `temperedLB` in vt
* LBAF when comparable models are available (e.g. no $\delta$)

@lifflander integrating your script to extract the computed solutions from them LP"s computed solution, could be made part of this issue too.

### PR DESCRIPTION
**Pull request by ppebay**
Resolves #8

### CODE REVIEW

**Comment by ppebay** [comment]
Sanity check, following the addition of ability to report full as well as summarized solutions, firstly for the load-only case, as expected:

Screenshot 2024-09-08 at 18 56 57

**Comment by ppebay** [comment]
Now, with the same configuration except for the requirement to preserve the block-clusters, now activated, we obtain the following result (where W_max cannot be brought down to less than 2.5, which we knew but could not inspect thus far):

Screenshot 2024-09-08 at 19 08 23

**Review by maxime-bfsquall — COMMENTED** [review]
Nothing to report

**Review by tlamonthezie — APPROVED** [review]
Technically looks good. Is is correctly working with new detailed solution output.
Note:  if file becomes too big at some point we could envisage in the future to split the ccm_milp module into multiple files.

**Review by maxime-bfsquall — APPROVED** [review]

**Pull request merged**
